version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    # Security updates have a separate, internal limit of ten open pull requests
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Paris"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: k8s.io/*
        update-types: [version-update:semver-major, version-update:semver-minor]
