min_version: 1.7.0

pre-commit:
  piped: true
  jobs:
    - name: generate manifests and code
      run: make manifests generate
      glob: "{api/**/*.go,internal/webhook/**/*.go,internal/controller/**/*.go,PROJECT}"
      stage_fixed: true
    - name: lint and fix
      run: make lint-fix
      glob: "**/*.go"
      stage_fixed: true

pre-push:
  jobs:
    - name: smoke tests
      run: make test-short

commit-msg:
  jobs:
    - name: lint commit message
      run: COMMIT_MSG_FILE={1} make conform
