import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';
import { docsVersionsLoader } from 'starlight-versions/loader';

// src/content/docs is generated by `npm run sync-docs` (copies ../docs +
// src/content/overlay + versioned snapshots) and is gitignored; the default
// docsLoader reads it. The `versions` collection holds the per-version sidebar
// configs read by the starlight-versions plugin (src/content/versions/*.json,
// committed — see astro.config.mjs and the versioned-docs/ source root).
export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
	versions: defineCollection({ loader: docsVersionsLoader() }),
};
