import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// src/content/docs is generated by `npm run sync-docs` (copies ../docs +
// src/content/overlay) and is gitignored; the default docsLoader reads it.
export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
