import { defineCollection } from 'astro:content';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';
import { docsVersionsLoader } from 'starlight-versions/loader';

// src/content/docs is generated by `npm run sync-docs` (copies ../docs +
// src/content/overlay + versioned snapshots) and is gitignored; the default
// docsLoader reads it. The `versions` collection holds the per-version sidebar
// configs read by the starlight-versions plugin (src/content/versions/*.json,
// committed — see astro.config.mjs and the versioned-docs/ source root).
//
// The `i18n` collection (src/content/i18n/*.json, committed) overrides Starlight
// UI strings — here, the starlight-versions notice wording, so an archived
// version reads as a tagged release rather than "outdated" (the site root is the
// in-development `main` docs, and archived slugs are the stable releases).
export const collections = {
	docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
	versions: defineCollection({ loader: docsVersionsLoader() }),
	i18n: defineCollection({ loader: i18nLoader(), schema: i18nSchema() }),
};
