# permissions for end users to view cachedimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cachedimage-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-image-keeper
    app.kubernetes.io/part-of: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
  name: cachedimage-viewer-role
rules:
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages/status
  verbs:
  - get
