# permissions for end users to edit cachedimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
  name: kuik-cachedimage-editor-role
rules:
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - cachedimages/status
  verbs:
  - get
