# permissions for end users to view repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-image-keeper
    app.kubernetes.io/managed-by: kustomize
  name: kuik-repository-viewer-role
rules:
- apiGroups:
  - kuik.enix.io
  resources:
  - repositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - repositories/status
  verbs:
  - get
