############
# v2       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterReplicatedImageSet
metadata:
  name: docker-library
spec:
  upstreams:
    - imageFilter:
        include:
          - /docker/library/.+
      path: /docker/library/
      priority: 10
      registry: public.ecr.aws
    - imageFilter:
        include:
          - /library/[^/]+
      path: /library/
      priority: 20
      registry: mirror.gcr.io
    - imageFilter:
        include:
          - /library/[^/]+
      path: /library/
      priority: 30
      registry: docker.io
---
#################
# adunand rev2  #
#################
apiVersion: kuik.enix.io/v2alpha1
kind: ClusterImageRouter
metadata:
  name: docker-library
spec:
  alternatives:
  - prefix: public.ecr.aws/docker/library/
  - prefix: mirror.gcr.io/library/
  - prefix: docker.io/library/
---
#################
# adunand rev3  #
#################
apiVersion: kuik.enix.io/v2alpha1
kind: ImageAlternative
metadata:
  name: docker-library
spec:
  alternatives:
  - public.ecr.aws/docker/library/
  - mirror.gcr.io/library/
  - docker.io/library/
---
############
# jpetazzo #
############
---
############
# plaffitt #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterImageRouter
metadata:
  name: docker-library
spec:
  alternatives:
  - public.ecr.aws/docker/library/   # priority 10 → first
  - mirror.gcr.io/library/           # priority 20
  - docker.io/library/               # priority 30
