############
# v2       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterReplicatedImageSet
metadata:
  name: thanos
spec:
  upstreams:
    - imageFilter:
        include:
          - /thanos/thanos:.+
      path: /thanos/thanos
      priority: 10
      registry: quay.io
    - imageFilter:
        include:
          - /thanosio/thanos:.+
      path: /thanosio/thanos
      priority: 20
      registry: docker.io
---
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterReplicatedImageSet
metadata:
  name: prometheus
spec:
  upstreams:
    - imageFilter:
        include:
          - /prometheus/.*
      path: /prometheus/
      priority: 10
      registry: quay.io
    - imageFilter:
        include:
          - /prom/.+
      path: /prom/
      priority: 20
      registry: docker.io
---
#################
# adunand rev2  #
#################
apiVersion: kuik.enix.io/v2alpha1
kind: ClusterImageRouter
metadata:
  name: thanos
spec:
  alternatives:
  - prefix: quay.io/thanos/thanos
  - prefix: docker.io/thanosio/thanos
---
apiVersion: kuik.enix.io/v2alpha1
kind: ClusterImageRouter
metadata:
  name: prometheus
spec:
  alternatives:
  - prefix: quay.io/prometheus/
  - prefix: docker.io/prom/
---
#################
# adunand rev3  #
#################
apiVersion: kuik.enix.io/v2alpha1
kind: ImageAlternative
metadata:
  name: thanos
spec:
  alternatives:
  - quay.io/thanos/thanos
  - docker.io/thanosio/thanos
---
apiVersion: kuik.enix.io/v2alpha1
kind: ImageAlternative
metadata:
  name: prometheus
spec:
  alternatives:
  - quay.io/prometheus/
  - docker.io/prom/
---
############
# jpetazzo #
############
---
############
# plaffitt #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterImageRouter
metadata:
  name: thanos
spec:
  alternatives:
  - quay.io/thanos/thanos       # whole-repository prefix — captured suffix is just ":tag"
  - docker.io/thanosio/thanos
---
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterImageRouter
metadata:
  name: prometheus
spec:
  alternatives:
  - quay.io/prometheus/   # org-level prefix — suffix is "<repo>:tag"
  - docker.io/prom/
