############
# v2       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterReplicatedImageSet
metadata:
  name: thanos
spec:
  upstreams:
    - imageFilter:
        include:
          - /thanos/thanos:.+
      path: /thanos/thanos
      priority: 10
      registry: quay.io
    - imageFilter:
        include:
          - /thanosio/thanos:.+
      path: /thanosio/thanos
      priority: 20
      registry: docker.io
---
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterReplicatedImageSet
metadata:
  name: prometheus
spec:
  upstreams:
    - imageFilter:
        include:
          - /prometheus/.*
      path: /prometheus/
      priority: 10
      registry: quay.io
    - imageFilter:
        include:
          - /prom/.+
      path: /prom/
      priority: 20
      registry: docker.io
---
############
# v3       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ImageAlternative
metadata:
  name: thanos
spec:
  alternatives:
    - imagePrefix: quay.io/thanos/thanos
    - imagePrefix: docker.io/thanosio/thanos
---
apiVersion: kuik.enix.io/v1alpha1
kind: ImageAlternative
metadata:
  name: prometheus
spec:
  alternatives:
    - imagePrefix: quay.io/prometheus/
    - imagePrefix: docker.io/prom/
