############
# v2       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ReplicatedImageSet
metadata:
  name: x509-certificate-exporter
  namespace: monitoring
spec:
  upstreams:
    - imageFilter:
        include:
          - /enix/x509-certificate-exporter:.+
      path: /enix/
      priority: 10
      registry: quay.io
    - imageFilter:
        include:
          - /enix/x509-certificate-exporter:.+
      path: /enix/
      priority: 20
      registry: ghcr.io
    - imageFilter:
        include:
          - /enix/x509-certificate-exporter:.+
      path: /enix/
      priority: 30
      registry: docker.io
---
############
# v3       #
############
apiVersion: kuik.enix.io/v2alpha1
kind: ImageAlternative
metadata:
  name: x509-certificate-exporter
spec:
  alternatives:
    - quay.io/enix/x509-certificate-exporter
    - ghcr.io/enix/x509-certificate-exporter
    - docker.io/enix/x509-certificate-exporter
