############
# v2       #
############
apiVersion: kuik.enix.io/v1alpha1
kind: ClusterImageSetAvailability
metadata:
  name: all
spec:
  imageFilter:
    exclude:
      - registry.example.com/mirror/.+
    include:
      - .+
  unusedImageExpiry: 168h
---
############
# v3       #
############
apiVersion: kuik.enix.io/v2alpha1
kind: ImageMonitor
metadata:
  name: all
spec:
  podSelector:
    matchExpressions:
      - key: kuik-monitor-ignore
        operator: DoesNotExist
  unusedImageExpiry: 168h
