---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-image-keeper.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-image-keeper.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-image-keeper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kube-image-keeper.serviceAccountName" . }}-leader-election
roleRef:
  kind: ClusterRole
  name: {{ include "kube-image-keeper.serviceAccountName" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-image-keeper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
