apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-controllers
  labels:
    {{- include "kube-image-keeper.controllers-labels" . | nindent 4 }}
spec:
  {{- with .Values.controllers.replicas }}
  replicas: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-image-keeper.controllers-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controllers.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-image-keeper.controllers-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controllers.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-image-keeper.serviceAccountName" . }}
      {{- if .Values.controllers.priorityClassName }}
      priorityClassName: {{ .Values.controllers.priorityClassName | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.controllers.podSecurityContext | nindent 8 }}
      containers:
        - name: cache-manager
          securityContext:
            {{- toYaml .Values.controllers.securityContext | nindent 12 }}
          image: "{{ .Values.controllers.image.repository }}:{{ .Values.controllers.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controllers.image.pullPolicy }}
          command:
            - manager
            - -leader-elect
            - -expiry-delay={{ .Values.cachedImagesExpiryDelay }}
            - -proxy-port={{ .Values.proxy.hostPort }}
            - -registry-endpoint={{ include "kube-image-keeper.fullname" . }}-registry:5000
            - -max-concurrent-cached-image-reconciles={{ .Values.controllers.maxConcurrentCachedImageReconciles }}
            - -zap-log-level={{ .Values.controllers.verbosity }}
            {{- range .Values.controllers.webhook.ignoredImages }}
            - -ignore-images={{- . }}
            {{- end }}
            {{- range .Values.architectures }}
            - -arch={{- . }}
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          {{- with .Values.controllers.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.controllers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "kube-image-keeper.fullname" . }}-webhook-server-cert
