{{- if .Values.registry.garbageCollection.schedule }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-registry-restart
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-image-keeper.fullname" . }}-registry-restart
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-image-keeper.fullname" . }}-registry-restart
    namespace: {{ .Release.Namespace }}
{{- end }}
