{{- if .Values.registry.garbageCollectionSchedule }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-restart
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: ["registry"]
    verbs: ["get", "patch", "list", "watch"]
{{- end }}
