{{- if .Values.registry.garbageCollectionSchedule }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-registry-restart
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["statefulsets"]
    resourceNames: ["{{ include "kube-image-keeper.fullname" . }}-registry"]
    verbs: ["get", "patch", "list", "watch"]
{{- end }}
