apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-manager-metrics
  labels:
    {{- include "kube-image-keeper.manager-labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "kube-image-keeper.manager-selectorLabels" . | nindent 4 }}
