{{- $tls := dict -}}
{{- with .Values.insecureRegistries -}}
  {{- $_ := set $tls "insecureRegistries" . -}}
{{- end -}}
{{- with .Values.rootCertificateAuthorities.keys -}}
  {{- $paths := list -}}
  {{- range . -}}
    {{- $paths = append $paths (printf "%s/%s" (include "kube-image-keeper.rootCAMountPath" $) .) -}}
  {{- end -}}
  {{- $_ := set $tls "rootCertificateAuthorities" $paths -}}
{{- end -}}
{{- $config := deepCopy (default (dict) .Values.configuration) -}}
{{- if $tls -}}
  {{- $existingTls := default (dict) (get $config "tls") -}}
  {{- $_ := set $config "tls" (merge $existingTls $tls) -}}
{{- end -}}
{{- if $config }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-manager-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{- $config | toYaml | nindent 4 }}
{{- end }}
