{{- if .Values.metricsService.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-metrics
  labels:
    {{- include "kube-image-keeper.labels" . | nindent 4 }}
    {{- with .Values.metricsService.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.metricsService.port }}
    targetPort: metrics
  selector:
    {{- include "kube-image-keeper.selectorLabels" . | nindent 4 }}
{{- end }}
