{{- if .Values.registry.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-image-keeper.registry-serviceAccountName" . }}
  labels:
    {{- include "kube-image-keeper.labels" . | nindent 4 }}
    {{- with .Values.registry.serviceAccount.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
    {{- end }}
  {{- with .Values.registry.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
