{{- if .Values.registryUI.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-registry-ui
  labels:
    {{- include "kube-image-keeper.registry-ui-labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kube-image-keeper.registry-ui-selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.registryUI.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-image-keeper.registry-ui-selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.registryUI.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.registryUI.podSecurityContext | nindent 8 }}
      containers:
        - name: registry-ui
          securityContext:
            {{- toYaml .Values.registryUI.securityContext | nindent 12 }}
          image: {{ .Values.registryUI.image.repository }}:{{ .Values.registryUI.image.tag }}
          imagePullPolicy: {{ .Values.registryUI.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.registryUI.resources | nindent 12 }}
          env:
            - name: REGISTRY_HOST
              value: {{ include "kube-image-keeper.fullname" . }}-registry
            - name: REGISTRY_PORT
              value: "5000"
            - name: REGISTRY_PROTOCOL
              value: "http"
            - name: SSL_VERIFY
              value: "false"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "kube-image-keeper.fullname" . }}-registry-ui-basic-auth
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kube-image-keeper.fullname" . }}-registry-ui-basic-auth
                  key: password
      {{- with .Values.registryUI.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registryUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registryUI.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
