{{- $defaultSpec := .Values.registryMonitors.defaultSpec }}
{{- range $registry, $value := .Values.registryMonitors.items }}
{{- $spec := $value | default dict }}
apiVersion: kuik.enix.io/v1alpha1
kind: RegistryMonitor
metadata:
  name: {{ $spec.name | default (regexReplaceAll "^[-\\.]+|[-\\.]+$" (regexReplaceAll "[.-]{2,}" (regexReplaceAll "[^a-z0-9-.]" ($registry | lower) "-") "-") "") }}
spec:
  registry: {{ $registry }}
  interval: {{ $spec.interval | default $defaultSpec.interval }}
  maxPerInterval: {{ $spec.maxPerInterval | default $defaultSpec.maxPerInterval }}
  parallel: {{ $spec.parallel | default $defaultSpec.parallel }}
  method: {{ $spec.method | default $defaultSpec.method }}
---
{{- end }}
