{{- if .Values.installCRD -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repositories.kuik.enix.io
spec:
  group: kuik.enix.io
  names:
    kind: Repository
    listKind: RepositoryList
    plural: repositories
    shortNames:
    - repo
    singular: repository
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Repository is the Schema for the repositories API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RepositorySpec defines the desired state of Repository
            properties:
              name:
                type: string
            required:
            - name
            type: object
          status:
            description: RepositoryStatus defines the observed state of Repository
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end -}}
