apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-image-keeper.fullname" . }}-registry
  labels:
    {{- include "kube-image-keeper.registry-labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - name: docker-registry
      port: 5000
      targetPort: 5000
    - name: registry-metrics
      port: 5001
      targetPort: 5001
  selector:
    {{- include "kube-image-keeper.registry-selectorLabels" . | nindent 4 }}
