apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuik-serving-cert
spec:
  dnsNames:
  - kuik-webhook.{{ .Release.Namespace }}.svc
  - kuik-webhook.{{ .Release.Namespace }}.svc.cluster.local
  secretName: webhook-server-cert
  issuerRef:
    {{- toYaml .Values.controllers.webhook.certificateIssuerRef | nindent 4 }}
---
{{- if .Values.controllers.webhook.createCertificateIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kuik-selfsigned-issuer
spec:
  selfSigned: {}
{{- end -}}
