- apiGroups:
  - kuik.enix.io
  resources:
  - imagealternatives
  - imagemirrors
  - imagemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuik.enix.io
  resources:
  - imagealternatives/finalizers
  - imagemirrors/finalizers
  - imagemonitors/finalizers
  verbs:
  - update
- apiGroups:
  - kuik.enix.io
  resources:
  - imagealternatives/status
  - imagemirrors/status
  - imagemonitors/status
  verbs:
  - get
  - patch
  - update
