name: Lint

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check generated files
        run: |
          make manifests generate
          git diff --exit-code

      - name: Check formatting
        run: |
          make fmt
          git diff --exit-code

      - name: Run lint
        run: make lint
