name: Manual build

on:
  workflow_dispatch:

concurrency:
  group: manual-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  # semver:
  #   name: Semantic Version (dry-run)
  #   runs-on: ubuntu-24.04
  #   outputs:
  #     published: ${{ steps.dry-run.outputs.new_release_published }}
  #     last: ${{ steps.dry-run.outputs.last_release_version }}
  #     version: ${{ steps.dry-run.outputs.new_release_version }}
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false
  #     - name: Run semantic-release (dry-run)
  #       id: dry-run
  #       uses: cycjimmy/semantic-release-action@v4
  #       with:
  #         dry_run: true
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
  #     - name: Inspect semantic-release (dry-run) outcome
  #       shell: python
  #       env:
  #         SR_LAST: ${{ steps.dry-run.outputs.last_release_version }}
  #         SR_VERSION: ${{ steps.dry-run.outputs.new_release_version }}
  #       run: |
  #         import os
  #         print("Previous version: {}, next version: {}".format(os.environ["SR_LAST"], os.environ["SR_VERSION"]))
  #
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    # needs:
    #   - semver
    with:
      REPO_IMAGE: ${{ vars.REPO_IMAGE }}
      REPO_CHART: ${{ vars.REPO_CHART }}
      # VERSION: ${{ needs.semver.outputs.version}}-manual-${{ github.ref_name }}-${{ github.sha }}
      VERSION: 0.0.0-manual-${{ github.ref_name }}-${{ github.sha }}
      PRERELEASE: true
    secrets:
      REPO_LOGIN: ${{ secrets.QUAY_USERNAME }}
      REPO_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
      GH_TOKEN_PUBLISH_HELM_CHART: ${{ secrets.GH_TOKEN_PUBLISH_HELM_CHART }}
